### ISSUE TITLE
malloc, calloc and free have been deprecated since C++11.

### ISSUE THREAD

**Issue by tirthasheshpatel** [Shrey-Viradiya/C-Plus-Plus#1]
https://github.com/Shrey-Viradiya/C-Plus-Plus/blob/c866ae1b7f34077d1f7ccf138e7af582a408034c/pointers.cpp#L23
This is `C` style of allocating memory. They (i.e: malloc, calloc, alloc, free) have been deprecated since `C++11`.

This is the way to allocate memory in `C++`.
```
int *arr = new int[SIZE];
```

You can free the memory simply by:
```
delete[] arr;
```

Alternatively, C++ provides a class `allocator` in the module `memory` that has functions to allocate memory faster and copy the objects present at old memory to the new memory in an efficient way.

Here's a simple use of `allocator`
```
#include <iostream>
#include <memory>

using std::cout;
using std::cin;
using std::allocator;

int main(int argc, int** argv)
{
    allocator<int> alloc;
    int *arr = alloc.allocate(SIZE);
    // use arr as you want to...
    for(int i=0;i<SIZE;i++) alloc.destroy(arr+i);
    alloc.deallocate(arr, SIZE);
}
```

**Comment by Shrey-Viradiya** [comment]
Thank you for your comments. I will sure look at it.
